### PR TITLE
fix(1384): SmartLDAP fixes and improvements

### LINKED ISSUE #1384: Deep memberOf in SmartLDAP is broken
**Describe the bug**
SmartLDAP configuration supports loading a tree of groups. Members of child groups outside the base group DN were not honored. 

**To Reproduce**
1. Set up an LDAP service with memberOf module and optionally logging
2. Configure a group with member group that has a member group that has 'student' as a member, for example:
  ```
dn: uid=student,ou=People,dc=apereo,dc=org
objectClass: inetOrgPerson
objectClass: eduPerson
uid: student
givenName: Steve
sn: Smith
cn: Steve Smith
displayName: Steven Smith
mail: steve.smith@apereo.org
telephoneNumber: (800) 555-1234
eduPersonPrimaryAffiliation: student
ou: People

dn: cn=Sub Sub Special Students,ou=Groups2,dc=apereo,dc=org
objectClass: groupOfNames
cn: Sub Sub Special Students
member: uid=student,ou=People,dc=apereo,dc=org

dn: cn=Sub Special Students,ou=Groups,dc=apereo,dc=org
objectClass: groupOfNames
cn: Sub Special Students
member: cn=Sub Sub Special Students,ou=Groups2,dc=apereo,dc=org

dn: cn=Special Students,ou=Groups,dc=apereo,dc=org
objectClass: groupOfNames
cn: Special Students
member: cn=Sub Special Students,ou=Groups,dc=apereo,dc=org
  ```
  May need to run `ldapmodify` to add `memberOf` values that are the inverse of `member`, for example:
  ```
dn: uid=student,ou=People,dc=apereo,dc=org
changetype: modify
replace: memberOf
memberOf: cn=Sub Sub Special Students,ou=Groups2,dc=apereo,dc=org
  ```
3. Configure uPortal-start to use PR SNAPSHOT of uPortal in `gradle.properties`
  ```
uPortalVersion=5.3.3-SNAPSHOT
  ```
4. Configure uPortal-start to use this LDAP via `uPortal.properties` 
  ```
ldap.defaultLdapContext.url=ldap://localhost:389/
ldap.defaultLdapContext.baseDn=ou=People,dc=apereo,dc=org
ldap.defaultLdapContext.user=cn=admin,dc=apereo,dc=org
ldap.defaultLdapContext.password=*****
ldap.smartLdapContext.url=ldap://localhost:389/
ldap.smartLdapContext.baseDn=dc=apereo,dc=org
ldap.smartLdapContext.user=cn=admin,dc=apereo,dc=org
ldap.smartLdapContext.password=*****
  ```
5. Configure uPortal-start with uPortal override `overlays/uPortal/src/main/resources/logback.xml` with:
  ```
  <logger name="org.apereo.portal.groups.smartldap" additivity="false" level="DEBUG">
    <appender-ref ref="PORTAL"/>
  </logger>
  <logger name="org.apereo.portal.groups.ldap" additivity="false" level="DEBUG">
    <appender-ref ref="PORTAL"/>
  </logger>
  ``` 
6. `Add overlays/uPortal/src/main/resources/properties/groups/compositeGroupServices.xml` from uPortal repo, un-commenting the `smartldap` service
7. Add a `uPortalLdapAttributeSource` bean in `overridesContext.xml` that uses LDAP to get `memberOf` values for test uses, like `student`.
8. Add `smartLdapGroupStore` , `smartLdapContext` and `smartLdapContext_target` to `overridesContext.xml`, for example:
  ```
  <bean id="smartLdapGroupStore" class="org.apereo.portal.groups.smartldap.SmartLdapGroupStore" lazy-init="false" depends-on="smartLdapContext">

    <!--
     | This property is the ContextSource instance that will be used to connect to LDAP.  Uncomment the
     | following to use the LDAP settings in ldapContext.xml for user attributes, or supply your own.
     +-->
    <!--
    -->
    <property name="ldapContext" ref="smartLdapContext"/>

    <!--
     | This property identifies the name of the Person Attribute that
     | lists the SmartLdap groups each person is a member of.
     +-->
    <property name="memberOfAttributeName" value="memberOf"/>

    <!--
     | BaseDn that will be passed to the search (not to the context).
     |
     | WARNING:  If you get an error like this...
     |   ...PartialResultException: [LDAP: error code 10...
     | it probably means your baseGroupDn isn't correct!
     +-->
    <property name="baseGroupDn" value="ou=Groups"/>

    <!--
     | This parameter is used to extract the id path of the groups
     | from their dn. The id path is expected to be catched from the first group
     | of the regex.
    <property name="childGroupKeyRegex" value="cn=(.*),ou=Groups,dc=apereo,dc=org"/>
    <property name="childGroupKeyRegex" value="cn=(.*),ou=.*,dc=apereo,dc=org"/>
     +-->

    <!--
     | This parameter is used to avoid performance problems with large people's members groups
     | on groups manager. Default value is false, so comment to disable.
     +-->
    <!--
    -->
    <property name="displayPersonMembers" value="true" />
    <!--
     | Group Tree Separator is used to set the char that is used to compose
     | Group Id in grouper that represent each tree paths.
     | Override it if the default value ":" doesn't match
    -->
    <!--<property name="groupTreeSeparator" value=":" />-->

    <!--
     | LDAP query string that will be passed to the search.
     +-->
    <property name="filter" value="(objectClass=groupOfNames)"/>

    <!--
     | Period, in seconds, after which SmartLdap will drop and re-init the groups
     | tree.  A value of zero or less (negative) disables this feature.
     +-->
    <property name="groupsTreeRefreshIntervalSeconds" value="900"/>

    <!--
     | These next 2 properties tell smartLdap whether to gather additional groups that
     | are members of groups returned by the first baseGroupDn and filter, and where to
     | look if so.
     |
     |   - resolveMemberGroups=[true|false]
     |   - resolveDn={a different, broader baseGroupDn than the one above}
     |
     | Here's how it works:  smartLdap will first collect all groups under the
     | baseGroupDn specified above.  If 'resolveMemberGroups' is enabled, it will
     | also search for additional groups (found within the 'resolveDn' specified
     | here) that are members of groups in the first collection.
     +-->
    <property name="resolveMemberGroups" value="true"/>
    <property name="resolveDn" value="ou=Groups2"/><!--Used with resolveMemberGroups -->

    <!--
     | This property identifies the org.springframework.ldap.core.AttributesMapper
     | implementation used in reading the groups records from LDAP.
     +-->
    <property name="attributesMapper">
      <bean id="attributesMapper" class="org.apereo.portal.groups.smartldap.SimpleAttributesMapper">
        <!--
         | Name of the group attribute that tells you its key.
         +-->
        <property name="keyAttributeName">
          <value>seeAlso</value>
        </property>
        <!--
         | Name of the group attribute that tells you its name.
         +-->
        <property name="groupNameAttributeName">
          <value>cn</value>
        </property>
        <!--
         | Name of the group attribute that lists its members.
         +-->
        <property name="membershipAttributeName">
          <value>member</value>
        </property>
      </bean>
    </property>
  </bean>
  <bean id="smartLdapContext" class="org.springframework.ldap.pool.factory.PoolingContextSource">
    <property name="contextSource" ref="smartLdapContext_target"/>
    <property name="dirContextValidator">
      <bean class="org.springframework.ldap.pool.validation.DefaultDirContextValidator">
        <property name="searchControls">
          <bean class="javax.naming.directory.SearchControls">
            <property name="searchScope"><util:constant static-field="javax.naming.directory.SearchControls.SUBTREE_SCOPE" /></property>
            <property name="countLimit" value="1" />
            <property name="returningAttributes"><list><value>objectclass</value></list></property>
            <property name="timeLimit" value="500" />
          </bean>
        </property>
      </bean>
    </property>
    <property name="minIdle" value="${ldap.defaultLdapContext.pool.minIdle:1}" />
    <property name="maxActive" value="${ldap.defaultLdapContext.pool.maxActive:32}" />
    <property name="maxIdle" value="${ldap.defaultLdapContext.pool.maxIdle:32}" />
    <property name="maxWait" value="${ldap.defaultLdapContext.pool.maxWait:1000}"/>
    <property name="testOnBorrow" value="${ldap.defaultLdapContext.pool.testOnBorrow:true}"/>
    <property name="testWhileIdle" value="${ldap.defaultLdapContext.pool.testWhileIdle:true}"/>
    <property name="timeBetweenEvictionRunsMillis" value="${ldap.defaultLdapContext.pool.timeBetweenEvictionRunsMillis:120000}"/>
    <property name="minEvictableIdleTimeMillis" value="${ldap.defaultLdapContext.pool.minEvictableIdleTimeMillis:900000}"/>
    <property name="numTestsPerEvictionRun" value="${ldap.defaultLdapContext.pool.numTestsPerEvictionRun:6}"/>
  </bean>

  <bean id="smartLdapContext_target" class="org.springframework.ldap.core.support.LdapContextSource">
    <property name="url" value="${ldap.smartLdapContext.url:}"/>
    <property name="base" value="${ldap.smartLdapContext.baseDn:}"/>
    <property name="userDn" value="${ldap.smartLdapContext.user:}"/>
    <property name="password" value="${ldap.smartLdapContext.password:}"/>
    <property name="pooled" value="${ldap.smartLdapContext.pooled:false}"/>
  </bean>
  ```

**Expected behavior**
Student should be a member of all three groups. This can be confirmed as Admin by reviewing user details in User Administration Portlet.

**Screenshots**
Expected results
image

### PR DESCRIPTION
**Pull request by bjagg**
Address small bugs in SmartLDAP code, add recursive getParents() method, and make child key modification optional.

Resolves #1384.

##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]
-   [x] documentation is changed or added

##### Description of change

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by bjagg** [comment]
@jgribonvald This PR extracts the child key modification into an external bean that will be autowired when added to a Spring Framework context. This should allow for your customization as well as support uPortal installations that need this to be unmodified.

File: uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SmartLdapGroupStore.java [hunk 1]
```diff
@@ -235,53 +240,69 @@ public IEntityGroup find(String key) throws GroupsException {
...
+        }
+        List<String> parentKeys = groupsTree.getParents().get(key);
+        parentKeys = parentKeys != null ? parentKeys : Collections.emptyList();
+        log.debug("Parent keys for {}: {}", key, String.join(",", parentKeys));
+        for (String parentKey : parentKeys) {
+            IEntityGroup parent = groupsTree.getGroups().get(parentKey);
+            if (parent == null) {
+                log.warn("Group tree inconsistent -- missing parent: {}", parentKey);
+            } else if (groups.contains(parent)) {
+                log.warn("Parent found multiple times, could be recursion group tree!");
```
Comment (jgribonvald) [inline uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SmartLdapGroupStore.java]: May help if having parent id and group id provided into the log

File: uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SmartLdapGroupStore.java [hunk 2]
```diff
@@ -235,53 +240,72 @@ public IEntityGroup find(String key) throws GroupsException {
...
+        }
+        List<String> parentKeys = groupsTree.getParents().get(key);
+        parentKeys = parentKeys != null ? parentKeys : Collections.emptyList();
+        log.debug("Parent keys for {}: {}", key, String.join(",", parentKeys));
+        for (String parentKey : parentKeys) {
+            IEntityGroup parent = groupsTree.getGroups().get(parentKey);
+            if (parent == null) {
+                log.warn("Group tree inconsistent -- missing parent: {}", parentKey);
+            } else if (groups.contains(parent)) {
+                log.warn(
```
Comment (jgribonvald) [inline uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SmartLdapGroupStore.java]: This log could be an info level because several childs will have the same parent (in a group tree structure).
Even I don't know if there are case which will need to be logged, this part can be removed and next else should test if `!groups.contains(parent)`

Comment (jgribonvald) [reply uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SmartLdapGroupStore.java]: @bjagg : Is there a possibility to review this log ?
I would like to keep the info level on this class without a big number of this warn log (this warn is normal in my case as we make group tree decomposition from child and that we come back to parent and that all childs have a common parent, so there isn't need to warn about existing parent `groups.contains(parent)`)
